import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request'

const graphcms = new GraphQLClient('graphcms Content API')

const QUERY = gql`{
  postPractices {
    id
    title
    datePublished
    slug
    content {
      html
    }
    author {
      name
      avatar{
        url
      }
    }
    coverPhoto {
      publishedAt 
      createBy {
        id
      },
      url
      
    }
  }
}`

export async function getStaticProps() {
  const {postPractices} = await graphcms.request(QUERY);

  return {
    props: {
      postPractices,
    },
  };
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      </main>

    </div>
  )
}
